## importing pandas

In [ ]:
import pandas as pd

### opening a local csv file

In [2]:
df = pd.read_csv('academic Stress level - maintainance 1.csv')
df

,Timestamp,Your Academic Stage,Peer pressure,Academic pressure from your home,Study Environment,What coping strategy you use as a student?,"Do you have any bad habits like smoking, drinking on a daily basis?",What would you rate the academic competition in your student life,Rate your academic stress index
0,24/07/2025 22:05:39,undergraduate,4,5,Noisy,Analyze the situation and handle it with intel...,No,3,5
1,24/07/2025 22:05:52,undergraduate,3,4,Peaceful,Analyze the situation and handle it with intel...,No,3,3
2,24/07/2025 22:06:39,undergraduate,1,1,Peaceful,"Social support (friends, family)",No,2,4
3,24/07/2025 22:06:45,undergraduate,3,2,Peaceful,Analyze the situation and handle it with intel...,No,4,3
4,24/07/2025 22:08:06,undergraduate,3,3,Peaceful,Analyze the situation and handle it with intel...,No,4,5
...,...,...,...,...,...,...,...,...,...
135,17/08/2025 13:02:04,undergraduate,3,2,Peaceful,Analyze the situation and handle it with intel...,No,3,4
136,18/08/2025 14:36:00,undergraduate,4,2,disrupted,Analyze the situation and handle it with intel...,No,3,3
137,18/08/2025 17:13:52,undergraduate,3,3,Peaceful,Analyze the situation and handle it with intel...,No,2,4
138,18/08/2025 19:08:52,undergraduate,4,5,disrupted,"Social support (friends, family)",No,5,5
139,18/08/2025 22:40:13,undergraduate,4,2,Peaceful,"Social support (friends, family)",No,4,4

### opening a csv file from an url

In [3]:
import requests
from io import StringIO

url = " "  # yaha par kisi url ka paste karenge tab jake chalega
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers= headers)
data = StringIO(req.text)

pd.read_csv(data)

ModuleNotFoundError: No module named 'requests'

#### index_col parameter

In [4]:
pd.read_csv('academic Stress level - maintainance 1.csv',index_col = 'Timestamp' )  # jo default pandas index tha usko replace karne ke liye

,Your Academic Stage,Peer pressure,Academic pressure from your home,Study Environment,What coping strategy you use as a student?,"Do you have any bad habits like smoking, drinking on a daily basis?",What would you rate the academic competition in your student life,Rate your academic stress index
Timestamp,,,,,,,,
24/07/2025 22:05:39,undergraduate,4,5,Noisy,Analyze the situation and handle it with intel...,No,3,5
24/07/2025 22:05:52,undergraduate,3,4,Peaceful,Analyze the situation and handle it with intel...,No,3,3
24/07/2025 22:06:39,undergraduate,1,1,Peaceful,"Social support (friends, family)",No,2,4
24/07/2025 22:06:45,undergraduate,3,2,Peaceful,Analyze the situation and handle it with intel...,No,4,3
24/07/2025 22:08:06,undergraduate,3,3,Peaceful,Analyze the situation and handle it with intel...,No,4,5
...,...,...,...,...,...,...,...,...
17/08/2025 13:02:04,undergraduate,3,2,Peaceful,Analyze the situation and handle it with intel...,No,3,4
18/08/2025 14:36:00,undergraduate,4,2,disrupted,Analyze the situation and handle it with intel...,No,3,3
18/08/2025 17:13:52,undergraduate,3,3,Peaceful,Analyze the situation and handle it with intel...,No,2,4
18/08/2025 19:08:52,undergraduate,4,5,disrupted,"Social support (friends, family)",No,5,5
18/08/2025 22:40:13,undergraduate,4,2,Peaceful,"Social support (friends, family)",No,4,4

#### header parameter

### Skipsrows/nrows parameter

In [6]:
df = pd.read_csv('academic Stress level - maintainance 1.csv',skiprows=[0, 2, 4])
df

,24/07/2025 22:05:39,undergraduate,4,5,Noisy,Analyze the situation and handle it with intellect,No,3,5.1
0,24/07/2025 22:06:39,undergraduate,1,1,Peaceful,"Social support (friends, family)",No,2,4
1,24/07/2025 22:08:06,undergraduate,3,3,Peaceful,Analyze the situation and handle it with intel...,No,4,5
2,24/07/2025 22:08:13,undergraduate,3,3,Peaceful,Analyze the situation and handle it with intel...,No,4,4
3,24/07/2025 22:09:21,undergraduate,5,5,disrupted,Emotional breakdown (crying a lot),No,4,4
4,24/07/2025 22:10:06,undergraduate,3,2,Peaceful,"Social support (friends, family)",No,3,3
...,...,...,...,...,...,...,...,...,...
132,17/08/2025 13:02:04,undergraduate,3,2,Peaceful,Analyze the situation and handle it with intel...,No,3,4
133,18/08/2025 14:36:00,undergraduate,4,2,disrupted,Analyze the situation and handle it with intel...,No,3,3
134,18/08/2025 17:13:52,undergraduate,3,3,Peaceful,Analyze the situation and handle it with intel...,No,2,4
135,18/08/2025 19:08:52,undergraduate,4,5,disrupted,"Social support (friends, family)",No,5,5
136,18/08/2025 22:40:13,undergraduate,4,2,Peaceful,"Social support (friends, family)",No,4,4

In [17]:
df = pd.read_csv('academic Stress level - maintainance 1.csv',nrows=100)
df

,Timestamp,Your Academic Stage,Peer pressure,Academic pressure from your home,Study Environment,What coping strategy you use as a student?,"Do you have any bad habits like smoking, drinking on a daily basis?",What would you rate the academic competition in your student life,Rate your academic stress index
0,24/07/2025 22:05:39,undergraduate,4,5,Noisy,Analyze the situation and handle it with intel...,No,3,5
1,24/07/2025 22:05:52,undergraduate,3,4,Peaceful,Analyze the situation and handle it with intel...,No,3,3
2,24/07/2025 22:06:39,undergraduate,1,1,Peaceful,"Social support (friends, family)",No,2,4
3,24/07/2025 22:06:45,undergraduate,3,2,Peaceful,Analyze the situation and handle it with intel...,No,4,3
4,24/07/2025 22:08:06,undergraduate,3,3,Peaceful,Analyze the situation and handle it with intel...,No,4,5
...,...,...,...,...,...,...,...,...,...
95,26/07/2025 07:50:38,high school,3,3,Peaceful,Analyze the situation and handle it with intel...,No,3,4
96,26/07/2025 08:13:18,high school,2,3,Noisy,Emotional breakdown (crying a lot),No,3,4
97,26/07/2025 08:25:17,high school,1,2,Peaceful,Analyze the situation and handle it with intel...,No,5,3
98,26/07/2025 08:25:18,high school,4,4,disrupted,Emotional breakdown (crying a lot),No,2,5
99,26/07/2025 08:27:10,high school,4,3,Peaceful,Analyze the situation and handle it with intel...,No,4,4

### use_cols parameter

In [10]:
df = pd.read_csv('academic Stress level - maintainance 1.csv', usecols = ['Your Academic Stage','Study Environment'])
df

    Your Academic Stage Study Environment
0         undergraduate             Noisy
1         undergraduate          Peaceful
2         undergraduate          Peaceful
3         undergraduate          Peaceful
4         undergraduate          Peaceful
..                  ...               ...
135       undergraduate          Peaceful
136       undergraduate         disrupted
137       undergraduate          Peaceful
138       undergraduate         disrupted
139       undergraduate          Peaceful

[140 rows x 2 columns]

### squeeze parameters

In [16]:
df = pd.read_csv('academic Stress level - maintainance 1.csv')
df = df.squeeze()
df

,Timestamp,Your Academic Stage,Peer pressure,Academic pressure from your home,Study Environment,What coping strategy you use as a student?,"Do you have any bad habits like smoking, drinking on a daily basis?",What would you rate the academic competition in your student life,Rate your academic stress index
0,24/07/2025 22:05:39,undergraduate,4,5,Noisy,Analyze the situation and handle it with intel...,No,3,5
1,24/07/2025 22:05:52,undergraduate,3,4,Peaceful,Analyze the situation and handle it with intel...,No,3,3
2,24/07/2025 22:06:39,undergraduate,1,1,Peaceful,"Social support (friends, family)",No,2,4
3,24/07/2025 22:06:45,undergraduate,3,2,Peaceful,Analyze the situation and handle it with intel...,No,4,3
4,24/07/2025 22:08:06,undergraduate,3,3,Peaceful,Analyze the situation and handle it with intel...,No,4,5
...,...,...,...,...,...,...,...,...,...
135,17/08/2025 13:02:04,undergraduate,3,2,Peaceful,Analyze the situation and handle it with intel...,No,3,4
136,18/08/2025 14:36:00,undergraduate,4,2,disrupted,Analyze the situation and handle it with intel...,No,3,3
137,18/08/2025 17:13:52,undergraduate,3,3,Peaceful,Analyze the situation and handle it with intel...,No,2,4
138,18/08/2025 19:08:52,undergraduate,4,5,disrupted,"Social support (friends, family)",No,5,5
139,18/08/2025 22:40:13,undergraduate,4,2,Peaceful,"Social support (friends, family)",No,4,4

 ### encoding parameter

In [18]:
df = pd.read_csv('academic Stress level - maintainance 1.csv',encoding="utf-8")
df

,Timestamp,Your Academic Stage,Peer pressure,Academic pressure from your home,Study Environment,What coping strategy you use as a student?,"Do you have any bad habits like smoking, drinking on a daily basis?",What would you rate the academic competition in your student life,Rate your academic stress index
0,24/07/2025 22:05:39,undergraduate,4,5,Noisy,Analyze the situation and handle it with intel...,No,3,5
1,24/07/2025 22:05:52,undergraduate,3,4,Peaceful,Analyze the situation and handle it with intel...,No,3,3
2,24/07/2025 22:06:39,undergraduate,1,1,Peaceful,"Social support (friends, family)",No,2,4
3,24/07/2025 22:06:45,undergraduate,3,2,Peaceful,Analyze the situation and handle it with intel...,No,4,3
4,24/07/2025 22:08:06,undergraduate,3,3,Peaceful,Analyze the situation and handle it with intel...,No,4,5
...,...,...,...,...,...,...,...,...,...
135,17/08/2025 13:02:04,undergraduate,3,2,Peaceful,Analyze the situation and handle it with intel...,No,3,4
136,18/08/2025 14:36:00,undergraduate,4,2,disrupted,Analyze the situation and handle it with intel...,No,3,3
137,18/08/2025 17:13:52,undergraduate,3,3,Peaceful,Analyze the situation and handle it with intel...,No,2,4
138,18/08/2025 19:08:52,undergraduate,4,5,disrupted,"Social support (friends, family)",No,5,5
139,18/08/2025 22:40:13,undergraduate,4,2,Peaceful,"Social support (friends, family)",No,4,4

### Skip bad lines

In [19]:
df = pd.read_csv('academic Stress level - maintainance 1.csv',on_bad_lines="skip")
df

,Timestamp,Your Academic Stage,Peer pressure,Academic pressure from your home,Study Environment,What coping strategy you use as a student?,"Do you have any bad habits like smoking, drinking on a daily basis?",What would you rate the academic competition in your student life,Rate your academic stress index
0,24/07/2025 22:05:39,undergraduate,4,5,Noisy,Analyze the situation and handle it with intel...,No,3,5
1,24/07/2025 22:05:52,undergraduate,3,4,Peaceful,Analyze the situation and handle it with intel...,No,3,3
2,24/07/2025 22:06:39,undergraduate,1,1,Peaceful,"Social support (friends, family)",No,2,4
3,24/07/2025 22:06:45,undergraduate,3,2,Peaceful,Analyze the situation and handle it with intel...,No,4,3
4,24/07/2025 22:08:06,undergraduate,3,3,Peaceful,Analyze the situation and handle it with intel...,No,4,5
...,...,...,...,...,...,...,...,...,...
135,17/08/2025 13:02:04,undergraduate,3,2,Peaceful,Analyze the situation and handle it with intel...,No,3,4
136,18/08/2025 14:36:00,undergraduate,4,2,disrupted,Analyze the situation and handle it with intel...,No,3,3
137,18/08/2025 17:13:52,undergraduate,3,3,Peaceful,Analyze the situation and handle it with intel...,No,2,4
138,18/08/2025 19:08:52,undergraduate,4,5,disrupted,"Social support (friends, family)",No,5,5
139,18/08/2025 22:40:13,undergraduate,4,2,Peaceful,"Social support (friends, family)",No,4,4

### dtypes parameter

In [24]:
df = pd.read_csv('academic Stress level - maintainance 1.csv', dtype={"Age": int})
df

,Timestamp,Your Academic Stage,Peer pressure,Academic pressure from your home,Study Environment,What coping strategy you use as a student?,"Do you have any bad habits like smoking, drinking on a daily basis?",What would you rate the academic competition in your student life,Rate your academic stress index
0,24/07/2025 22:05:39,undergraduate,4,5,Noisy,Analyze the situation and handle it with intel...,No,3,5
1,24/07/2025 22:05:52,undergraduate,3,4,Peaceful,Analyze the situation and handle it with intel...,No,3,3
2,24/07/2025 22:06:39,undergraduate,1,1,Peaceful,"Social support (friends, family)",No,2,4
3,24/07/2025 22:06:45,undergraduate,3,2,Peaceful,Analyze the situation and handle it with intel...,No,4,3
4,24/07/2025 22:08:06,undergraduate,3,3,Peaceful,Analyze the situation and handle it with intel...,No,4,5
...,...,...,...,...,...,...,...,...,...
135,17/08/2025 13:02:04,undergraduate,3,2,Peaceful,Analyze the situation and handle it with intel...,No,3,4
136,18/08/2025 14:36:00,undergraduate,4,2,disrupted,Analyze the situation and handle it with intel...,No,3,3
137,18/08/2025 17:13:52,undergraduate,3,3,Peaceful,Analyze the situation and handle it with intel...,No,2,4
138,18/08/2025 19:08:52,undergraduate,4,5,disrupted,"Social support (friends, family)",No,5,5
139,18/08/2025 22:40:13,undergraduate,4,2,Peaceful,"Social support (friends, family)",No,4,4

### Convertors

In [43]:
def rename(name):
    if name == "undergraduate":
        return "UG"
    else :
        return name

In [44]:
rename("undergraduate")

'UG'

In [46]:
df = pd.read_csv('academic Stress level - maintainance 1.csv',converters={'Your Academic Stage':rename})
df

,Timestamp,Your Academic Stage,Peer pressure,Academic pressure from your home,Study Environment,What coping strategy you use as a student?,"Do you have any bad habits like smoking, drinking on a daily basis?",What would you rate the academic competition in your student life,Rate your academic stress index
0,24/07/2025 22:05:39,UG,4,5,Noisy,Analyze the situation and handle it with intel...,No,3,5
1,24/07/2025 22:05:52,UG,3,4,Peaceful,Analyze the situation and handle it with intel...,No,3,3
2,24/07/2025 22:06:39,UG,1,1,Peaceful,"Social support (friends, family)",No,2,4
3,24/07/2025 22:06:45,UG,3,2,Peaceful,Analyze the situation and handle it with intel...,No,4,3
4,24/07/2025 22:08:06,UG,3,3,Peaceful,Analyze the situation and handle it with intel...,No,4,5
...,...,...,...,...,...,...,...,...,...
135,17/08/2025 13:02:04,UG,3,2,Peaceful,Analyze the situation and handle it with intel...,No,3,4
136,18/08/2025 14:36:00,UG,4,2,disrupted,Analyze the situation and handle it with intel...,No,3,3
137,18/08/2025 17:13:52,UG,3,3,Peaceful,Analyze the situation and handle it with intel...,No,2,4
138,18/08/2025 19:08:52,UG,4,5,disrupted,"Social support (friends, family)",No,5,5
139,18/08/2025 22:40:13,UG,4,2,Peaceful,"Social support (friends, family)",No,4,4

### na_values parameter

In [49]:
df = pd.read_csv('academic Stress level - maintainance 1.csv', na_values=['No'])
df

,Timestamp,Your Academic Stage,Peer pressure,Academic pressure from your home,Study Environment,What coping strategy you use as a student?,"Do you have any bad habits like smoking, drinking on a daily basis?",What would you rate the academic competition in your student life,Rate your academic stress index
0,24/07/2025 22:05:39,undergraduate,4,5,Noisy,Analyze the situation and handle it with intel...,NaN,3,5
1,24/07/2025 22:05:52,undergraduate,3,4,Peaceful,Analyze the situation and handle it with intel...,NaN,3,3
2,24/07/2025 22:06:39,undergraduate,1,1,Peaceful,"Social support (friends, family)",NaN,2,4
3,24/07/2025 22:06:45,undergraduate,3,2,Peaceful,Analyze the situation and handle it with intel...,NaN,4,3
4,24/07/2025 22:08:06,undergraduate,3,3,Peaceful,Analyze the situation and handle it with intel...,NaN,4,5
...,...,...,...,...,...,...,...,...,...
135,17/08/2025 13:02:04,undergraduate,3,2,Peaceful,Analyze the situation and handle it with intel...,NaN,3,4
136,18/08/2025 14:36:00,undergraduate,4,2,disrupted,Analyze the situation and handle it with intel...,NaN,3,3
137,18/08/2025 17:13:52,undergraduate,3,3,Peaceful,Analyze the situation and handle it with intel...,NaN,2,4
138,18/08/2025 19:08:52,undergraduate,4,5,disrupted,"Social support (friends, family)",NaN,5,5
139,18/08/2025 22:40:13,undergraduate,4,2,Peaceful,"Social support (friends, family)",NaN,4,4

### loading a huge dataset in chunks

In [50]:
df = pd.read_csv('academic Stress level - maintainance 1.csv',chunksize= 30)
df

In [52]:
for chunk in df:
    print(chunk.shape)

(30, 9)
(30, 9)
(30, 9)
(20, 9)